-- MySQL Script generated by MySQL Workbench
-- Mon Aug 17 17:06:58 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mmwr_case
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mmwr_case
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mmwr_case` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mmwr_case` ;

-- -----------------------------------------------------
-- Table `mmwr_case`.`Case_Main`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmwr_case`.`Case_Main` ;

CREATE TABLE IF NOT EXISTS `mmwr_case`.`Case_Main` (
  `case_id` INT NOT NULL COMMENT '',
  `title` VARCHAR(140) NOT NULL COMMENT '',
  `overview` TEXT(500) NULL COMMENT '',
  `created_date` DATETIME NOT NULL COMMENT '',
  `publication_date` DATETIME NOT NULL COMMENT '',
  `case_text` LONGTEXT NULL COMMENT '',
  `abstract_text` LONGTEXT NULL COMMENT '',
  `additional_information` MEDIUMTEXT NULL COMMENT '',
  `current` TINYINT(1) NOT NULL COMMENT '',
  `archived` TINYINT(1) NOT NULL COMMENT '',
  `rating` INT NULL COMMENT '',
  `development_status` INT NOT NULL COMMENT '',
  `development_status_notes` TEXT(500) NULL COMMENT '',
  `display_status` INT NOT NULL COMMENT '',
  `available_cme_credits` TINYINT(1) NULL COMMENT '',
  `cme_release_date` DATETIME NULL COMMENT '',
  `cme_valid_until` DATETIME NULL COMMENT '',
  `number_cme_credits_available` INT NULL COMMENT '',
  PRIMARY KEY (`case_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmwr_case`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmwr_case`.`Question` ;

CREATE TABLE IF NOT EXISTS `mmwr_case`.`Question` (
  `question_id` INT NOT NULL COMMENT '',
  `case_id` INT NOT NULL COMMENT '',
  `sequence_id` INT NOT NULL COMMENT '',
  `post_pre` VARCHAR(5) NOT NULL COMMENT '',
  `question` TEXT(500) NOT NULL COMMENT '',
  PRIMARY KEY (`question_id`)  COMMENT '',
  UNIQUE INDEX `quesiton_id_UNIQUE` (`question_id` ASC)  COMMENT '',
  INDEX `fk_Question_Case_Main_idx` (`case_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Question_Case_Main`
    FOREIGN KEY (`case_id`)
    REFERENCES `mmwr_case`.`Case_Main` (`case_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmwr_case`.`Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmwr_case`.`Answer` ;

CREATE TABLE IF NOT EXISTS `mmwr_case`.`Answer` (
  `answer_id` INT NOT NULL COMMENT '',
  `question_id` INT NOT NULL COMMENT '',
  `case_id` INT NOT NULL COMMENT '',
  `answer` VARCHAR(250) NOT NULL COMMENT '',
  `correct` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`answer_id`)  COMMENT '',
  UNIQUE INDEX `answer_id_UNIQUE` (`answer_id` ASC)  COMMENT '',
  INDEX `fk_Answer_Question1_idx` (`question_id` ASC)  COMMENT '',
  INDEX `fk_Answer_Case_Main1_idx` (`case_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Answer_Question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `mmwr_case`.`Question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Answer_Case_Main1`
    FOREIGN KEY (`case_id`)
    REFERENCES `mmwr_case`.`Case_Main` (`case_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmwr_case`.`Rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmwr_case`.`Rating` ;

CREATE TABLE IF NOT EXISTS `mmwr_case`.`Rating` (
  `rating_id` INT NOT NULL COMMENT '',
  `case_id` INT NOT NULL COMMENT '',
  `user_id` INT NULL COMMENT '',
  `rating` INT NOT NULL COMMENT '',
  PRIMARY KEY (`rating_id`)  COMMENT '',
  UNIQUE INDEX `rating_id_UNIQUE` (`rating_id` ASC)  COMMENT '',
  INDEX `fk_Rating_Case_Main1_idx` (`case_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Rating_Case_Main1`
    FOREIGN KEY (`case_id`)
    REFERENCES `mmwr_case`.`Case_Main` (`case_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmwr_case`.`Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmwr_case`.`Image` ;

CREATE TABLE IF NOT EXISTS `mmwr_case`.`Image` (
  `image_id` INT NOT NULL COMMENT '',
  `case_id` INT NOT NULL COMMENT '',
  `sequence_id` VARCHAR(45) NOT NULL COMMENT '',
  `image_url` VARCHAR(250) NOT NULL COMMENT '',
  `featured` TINYINT(1) NOT NULL COMMENT '',
  `title` VARCHAR(140) NOT NULL COMMENT '',
  PRIMARY KEY (`image_id`)  COMMENT '',
  UNIQUE INDEX `image_id_UNIQUE` (`image_id` ASC)  COMMENT '',
  INDEX `fk_Image_Case_Main1_idx` (`case_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Image_Case_Main1`
    FOREIGN KEY (`case_id`)
    REFERENCES `mmwr_case`.`Case_Main` (`case_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmwr_case`.`Development_Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmwr_case`.`Development_Status` ;

CREATE TABLE IF NOT EXISTS `mmwr_case`.`Development_Status` (
  `development_status_id` INT NOT NULL COMMENT '',
  `description` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`development_status_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmwr_case`.`Display_Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mmwr_case`.`Display_Status` ;

CREATE TABLE IF NOT EXISTS `mmwr_case`.`Display_Status` (
  `display_status_id` INT NOT NULL COMMENT '',
  `description` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`display_status_id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
